name: injection-inversions-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - ipywidgets>=0.6.0
  - mkl
  - pip:
    - pymatsolver
    - discretize
    - git+https://github.com/simpeg/simpeg.git@feat/dc_fields_derivs
    - git+https://github.com/simpeg-research/casingSimulations.git

